# Generated by Django 6.0 on 2026-01-30 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_order_source'),
        ('promotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('promo_type', models.CharField(choices=[('FIRST_ORDER', 'First Order'), ('AUTO', 'Auto Applied'), ('COUPON', 'Coupon Code')], max_length=20)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('one_time_per_user', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promotion Usage',
                'verbose_name_plural': 'Promotion Usages',
            },
        ),
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='couponusage',
            name='promotions_coupon__5d6b2e_idx',
        ),
        migrations.AddField(
            model_name='promotionusage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='promotionusage',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.promotion'),
        ),
        migrations.AddField(
            model_name='promotionusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='couponusage',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='couponusage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='couponusage',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='promotionusage',
            unique_together={('user', 'promotion')},
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='CouponUsage',
        ),
    ]
