# Generated by Django 6.0 on 2026-01-21 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactInfo",
        ),
        migrations.DeleteModel(
            name="ContactMessage",
        ),
    ]
