# Generated by Django 6.0 on 2026-01-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_auth_provider_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="joined_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
