# Generated by Django 6.0 on 2026-01-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="replied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="reply",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("replied", "Replied")],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
