# Generated by Django 6.0 on 2026-01-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_contactmessage_replied_at_contactmessage_reply_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="number",
            field=models.CharField(max_length=16),
        ),
    ]
