# Generated by Django 6.0 on 2026-01-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_contactmessage_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitecontact",
            name="contact_number",
            field=models.CharField(max_length=16),
        ),
    ]
