# Generated by Django 6.0 on 2026-01-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_sitecontact_contact_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
