# Generated by Django 6.0 on 2026-01-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
