# Generated by Django 6.0 on 2026-01-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_alter_order_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
