# Generated by Django 6.0 on 2026-01-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_order_delivery_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_date",
            field=models.DateField(),
        ),
    ]
