# Generated by Django 6.0 on 2026-01-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_alter_order_delivery_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_items_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
