# Generated by Django 6.0 on 2026-01-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_order_order_items_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COD", "Cash on Delivery"),
                    ("UPI", "UPI"),
                    ("CARD", "Credit / Debit Card"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
