# Generated by Django 6.0 on 2026-01-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0009_alter_order_payment_method"),
        ("products", "0014_alter_sizevariant_price"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together={("order", "variant")},
        ),
    ]
