# Generated by Django 6.0 on 2026-01-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0013_payment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
