# Generated by Django 6.0 on 2026-01-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0014_delete_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
