# Generated by Django 6.0 on 2026-01-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0015_order_paid_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("COD", "Cash on Delivery"),
                    ("ONLINE", "Online Payment"),
                    ("UPI", "UPI"),
                    ("CARD", "Credit / Debit Card"),
                ],
                max_length=10,
            ),
        ),
    ]
