# Generated by Django 6.0 on 2026-01-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0017_migrate_payment_method_to_online"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("COD", "Cash on Delivery"), ("ONLINE", "Online Payment")],
                max_length=10,
            ),
        ),
    ]
