# Generated by Django 6.0 on 2026-01-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0018_alter_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancel_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CHANGED_MIND", "Changed my mind"),
                    ("WRONG_ADDRESS", "Wrong delivery address"),
                    ("FOUND_CHEAPER", "Found a better price elsewhere"),
                    ("ORDERED_BY_MISTAKE", "Ordered by mistake"),
                    ("DELIVERY_DELAY", "Delivery is taking too long"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
