# Generated by Django 6.0 on 2026-01-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('CART', 'Cart'), ('BUY_NOW', 'Buy Now')], default='CART', max_length=10),
        ),
    ]
