# Generated by Django 6.0 on 2026-02-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_auto_20260131_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='success_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
