# Generated by Django 6.0 on 2025-12-24 15:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "category_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="categories_image/")),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
