# Generated by Django 6.0 on 2025-12-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
