# Generated by Django 6.0 on 2025-12-27 06:04

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_best_before_product_nutritional_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.ImageField(upload_to=products.models.product_main_image_path),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to=products.models.product_gallery_path),
        ),
    ]
