# Generated by Django 6.0 on 2026-01-06 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_product_sku"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sizevariant",
            unique_together={("product", "size_name")},
        ),
    ]
