# Generated by Django 6.0 on 2026-01-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_sizevariant_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="base_unit",
            field=models.CharField(
                choices=[
                    ("kg", "Kilogram"),
                    ("g", "Gram"),
                    ("pc", "Piece"),
                    ("pkt", "Packet"),
                    ("ltr", "Litre"),
                    ("ml", "Millilitre"),
                ],
                default="g",
                max_length=10,
            ),
        ),
    ]
