# Generated by Django 6.0 on 2026-01-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_product_base_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="base_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="base_unit",
        ),
    ]
