# Generated by Django 6.0 on 2026-01-12 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_productreview"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productreview",
            name="email",
        ),
        migrations.RemoveField(
            model_name="productreview",
            name="name",
        ),
        migrations.RemoveField(
            model_name="productreview",
            name="title",
        ),
    ]
