# Generated by Django 6.0 on 2026-01-13 06:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0013_remove_productreview_email_remove_productreview_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sizevariant",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
